### ISSUE TITLE
[BUG] - Inventory Item assigned to wrong array

### ISSUE THREAD

**Issue by nhcarrigan** [RosaliaNightsong/discord-bot#118]
### What bug did you encounter?

Player defeated a slime and received a Small Health Potion. For some reason, this was saved to their equippable items array.

### What did you expect to happen?

This should have been assigned to the consumable items array.

### Screenshots

![image](https://user-images.githubusercontent.com/63889819/135875174-fb4a2980-8124-42ea-9dfb-72673f4824f8.png)

**Comment by luigieai** [comment]
I would love to look at this issue.

**Comment by luigieai** [comment]
![image](https://user-images.githubusercontent.com/5982809/135896694-0e2d9a11-f257-4ac8-b83b-a47103659bbf.png)
Solved the problem, but i found out that the bug is ocurring in every item drop because of a snippet of code, i'm right now looking for other cases and i'll submit a PR
