### ISSUE TITLE
[BUG] - Short Sword not found?

### ISSUE THREAD

**Issue by nhcarrigan** [RosaliaNightsong/discord-bot#119]
### What bug did you encounter?

The short sword data exists in the configs, but for some reason came up as missing.

### What did you expect to happen?

This item should have been found and awarded to the player.

### Screenshots

![image](https://user-images.githubusercontent.com/63889819/135876156-c220b41e-c76e-46dc-9a6f-53d59e99d09e.png)

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/135883425-33c4a254-5d7d-4add-9977-02ef0e16fa3f.png)

Oddly enough, worked for a later command.

**Comment by luigieai** [comment]
There's an easy way to force an short sword reward? When /adventure in another issue i never came across this issue, i always got the short sword in the correct way

**Comment by nhcarrigan** [comment]
This might have been a one off bug, since we're not able to reproduce it.

The bot was restarted between the first image and the second, so it could have been a compiler hiccup. I'll leave this open for now, but am going to block it until I have better reproduction steps (or can even confirm that it's still an issue).

**Comment by nhcarrigan** [comment]
Going to close this, as it hasn't been reproduced.
