### ISSUE TITLE
[BUG] - Properly save the cooldown

### ISSUE THREAD

**Issue by nhcarrigan** [RosaliaNightsong/discord-bot#124]
### What bug did you encounter?

In both the `handleDungeon` and `handleExplore` modules the `character.adventure.cooldown =` isn't necessarily saved.

### What did you expect to happen?

After that line in each of the files, add a `character.markModified("adventure");` to ensure the change is preserved in the next save call.

**Comment by lmpham1** [comment]
I'd like to give this issue a try! I notice that `handleRest` also has the `character.adventure.cooldown =`, should I add the `character.markModified("adventure");` after that file as well?

**Comment by nhcarrigan** [comment]
Good question! 

The `handleRest` file does have the necessary line, however:

https://github.com/RosaliaNightsong/discord-bot/blob/a2f46b3b4912ea08aaf62e1625b6ac94e65c61e4/src/modules/subcommands/adventure/handleRest.ts#L61

I'll go ahead and assign this issue to you!

**Comment by lmpham1** [comment]
I see, thanks! I'll work on it
