### ISSUE TITLE
[BUG] - `/rosalia about` command errors

### ISSUE THREAD

**Issue by nhcarrigan** [RosaliaNightsong/discord-bot#321]
### What bug did you encounter?

Currently, the `/rosalia about` command throws an error on use, because one of the buttons does not have a style value set.

### What did you expect to happen?

The command should respond with the expected embed.

### Additional information

This issue can be resolved by adding a `.setStyle("LINK")` call to the `inviteButton` chain:

https://github.com/RosaliaNightsong/discord-bot/blob/f5707d2d5a72f4f287fcd009fa463f6bddd90756/src/modules/subcommands/rosalia/handleAbout.ts#L45-L47

**Comment by BrianSpencerDev** [comment]
I suppose I could take this one on

**Comment by nhcarrigan** [comment]
Go for it!
