### ISSUE TITLE
[CHORE] - Move to CDN

### ISSUE THREAD

**Issue by naomi-lgbt** [RosaliaNightsong/discord-bot#570]
### What work needs to be performed?

We should move to use the CDN instances of our images.

- Update the [art command](https://github.com/RosaliaNightsong/discord-bot/blob/5b5a5b7ab3850cc56b5b429d482144737f18cf8f/src/modules/subcommands/rosalia/handleArt.ts#L26) to point to `https://cdn.naomi.lgbt/rosalia/art/${art.fileName.replace(/\s/g, "%20")}`

**Comment by abuna1985** [comment]
Can I work on this issue please.

**Comment by naomi-lgbt** [comment]
Go for it!
